

Tensors 
===

In [6]:
import torch
import numpy as np

### Initialiszing Tensor

**From a List**

In [13]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

**From a NumPy array**

In [14]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

**From another tensor**

In [15]:
x_ones = torch.ones_like(x_data) # retains properties of x_data
x_ones

tensor([[1, 1],
        [1, 1]])

In [16]:
x_rand = torch.rand_like(x_data, dtype=torch.float)    # changes datatype of x_data
x_rand

tensor([[0.8150, 0.4583],
        [0.8277, 0.3401]])

**With random or constant values**

In [17]:
rand_tensor = torch.rand(2,3)
ones_tensor = torch.ones(2,3,)
zeros_tensor = torch.zeros(2,3,4)

print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)


tensor([[0.9398, 0.7497, 0.3461],
        [0.0056, 0.4517, 0.4746]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


### Attributes of a Tensor

In [18]:
tensor = torch.rand(3,4)

print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 4])
torch.float32
cpu


--------------




### Operations on Tensors

**Moving tensor to GPU (if available)**

In [22]:
if torch.cuda.is_available():tensor = tensor.to('cuda')

**Standard numpy-like indexing and slicing**

In [25]:
tensor = torch.rand(4, 4)
tensor

tensor([[0.3603, 0.6069, 0.3247, 0.9653],
        [0.0784, 0.1865, 0.7182, 0.0802],
        [0.0524, 0.3287, 0.7905, 0.3699],
        [0.8245, 0.9899, 0.7018, 0.9608]])

In [27]:
print(tensor[0])        # tensor @ first index in tensor
print(tensor[:, 0])     # first elements of every tensor inside the tensor
print(tensor[..., -1])  # last elements of every tensor inside the tensorr

tensor([0.3603, 0.6069, 0.3247, 0.9653])
tensor([0.3603, 0.0784, 0.0524, 0.8245])
tensor([0.9653, 0.0802, 0.3699, 0.9608])


In [29]:
tensor[:,1] = 0  # changing value of the element @ second index of every tensor to Zero
tensor

tensor([[0.3603, 0.0000, 0.3247, 0.9653],
        [0.0784, 0.0000, 0.7182, 0.0802],
        [0.0524, 0.0000, 0.7905, 0.3699],
        [0.8245, 0.0000, 0.7018, 0.9608]])

**Joining Tensors** 

In [31]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)    # dim=1 means along the col. 
t1

tensor([[0.3603, 0.0000, 0.3247, 0.9653, 0.3603, 0.0000, 0.3247, 0.9653, 0.3603,
         0.0000, 0.3247, 0.9653],
        [0.0784, 0.0000, 0.7182, 0.0802, 0.0784, 0.0000, 0.7182, 0.0802, 0.0784,
         0.0000, 0.7182, 0.0802],
        [0.0524, 0.0000, 0.7905, 0.3699, 0.0524, 0.0000, 0.7905, 0.3699, 0.0524,
         0.0000, 0.7905, 0.3699],
        [0.8245, 0.0000, 0.7018, 0.9608, 0.8245, 0.0000, 0.7018, 0.9608, 0.8245,
         0.0000, 0.7018, 0.9608]])

**Arithmetic operations**



In [36]:
# Matrix Multiplication  (3 Ways (basically 2 ;))

print(tensor @ tensor.T)       

print(tensor.matmul(tensor.T))

y3 = torch.rand_like(tensor)
print(torch.matmul(tensor, tensor.T, out=y3))

tensor([[1.1670, 0.3388, 0.6326, 1.4524],
        [0.3388, 0.5284, 0.6015, 0.6457],
        [0.6326, 0.6015, 0.7644, 0.9534],
        [1.4524, 0.6457, 0.9534, 2.0954]])
tensor([[1.1670, 0.3388, 0.6326, 1.4524],
        [0.3388, 0.5284, 0.6015, 0.6457],
        [0.6326, 0.6015, 0.7644, 0.9534],
        [1.4524, 0.6457, 0.9534, 2.0954]])
tensor([[1.1670, 0.3388, 0.6326, 1.4524],
        [0.3388, 0.5284, 0.6015, 0.6457],
        [0.6326, 0.6015, 0.7644, 0.9534],
        [1.4524, 0.6457, 0.9534, 2.0954]])


In [37]:
# Element-wise Product

print(tensor * tensor)

print(tensor.mul(tensor))

z3 = torch.rand_like(tensor)
print(torch.mul(tensor, tensor, out=z3))

tensor([[0.1298, 0.0000, 0.1054, 0.9318],
        [0.0061, 0.0000, 0.5159, 0.0064],
        [0.0027, 0.0000, 0.6248, 0.1369],
        [0.6797, 0.0000, 0.4926, 0.9231]])
tensor([[0.1298, 0.0000, 0.1054, 0.9318],
        [0.0061, 0.0000, 0.5159, 0.0064],
        [0.0027, 0.0000, 0.6248, 0.1369],
        [0.6797, 0.0000, 0.4926, 0.9231]])
tensor([[0.1298, 0.0000, 0.1054, 0.9318],
        [0.0061, 0.0000, 0.5159, 0.0064],
        [0.0027, 0.0000, 0.6248, 0.1369],
        [0.6797, 0.0000, 0.4926, 0.9231]])


**Single-element tensors** (one-element tensor can be converted to a python
numerical value using ``item()``)



In [38]:
agg = tensor.sum()
print(agg)

agg_item = agg.item()  
print(agg_item, type(agg_item))

tensor(6.2269)
6.226935386657715 <class 'float'>


**In-place operations**

In [39]:
print(tensor)
tensor.add_(5)   # adds 5 inplace to each element of the tensor
print(tensor)

tensor([[0.3603, 0.0000, 0.3247, 0.9653],
        [0.0784, 0.0000, 0.7182, 0.0802],
        [0.0524, 0.0000, 0.7905, 0.3699],
        [0.8245, 0.0000, 0.7018, 0.9608]])
tensor([[5.3603, 5.0000, 5.3247, 5.9653],
        [5.0784, 5.0000, 5.7182, 5.0802],
        [5.0524, 5.0000, 5.7905, 5.3699],
        [5.8245, 5.0000, 5.7018, 5.9608]])


--------------





### Bridge with NumPy
~~~~~~~~~~~~~~~~~
Tensors on the CPU and NumPy arrays can share their underlying memory
locations, and changing one will change the other.



**Tensor to NumPy array**

In [40]:
t = torch.ones(5)
print(t)
n = t.numpy()
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


***A change in the tensor reflects in the NumPy array***

In [43]:
t.add_(1)  # adding 1 inplace to t 
print(t)
print(n)  # value of n also changes

tensor([4., 4., 4., 4., 4.])
[4. 4. 4. 4. 4.]


**NumPy array to Tensor**

In [44]:
n = np.ones(5)
t = torch.from_numpy(n)

***Changes in the NumPy array reflects in the tensor***

In [45]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
